import { Public_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
});

const sfMono = localFont({
  src: [
    {
      path: "../fonts/sf-mono/SFMonoLight.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/sf-mono/SFMonoLightItalic.woff",
      weight: "300",
      style: "italic",
    },
    {
      path: "../fonts/sf-mono/SFMonoRegular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/sf-mono/SFMonoRegularItalic.woff",
      weight: "400",
      style: "italic",
    },
    {
      path: "../fonts/sf-mono/SFMonoMedium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/sf-mono/SFMonoMediumItalic.woff",
      weight: "500",
      style: "italic",
    },
    {
      path: "../fonts/sf-mono/SFMonoSemibold.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "../fonts/sf-mono/SFMonoMediumItalic.woff",
      weight: "600",
      style: "italic",
    },
    {
      path: "../fonts/sf-mono/SFMonoBold.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/sf-mono/SFMonoHeavy.woff",
      weight: "800",
      style: "normal",
    },
    {
      path: "../fonts/sf-mono/SFMonoHeavyItalic.woff",
      weight: "800",
      style: "italic",
    },
  ],
  variable: "--font-sf-mono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/site.webmanifest",
  icons: {
    icon: "/favicon/favicon.ico",
    shortcut: "/favicon/favicon-96x96.png",
    apple: "/favicon/apple-touch-icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${publicSans.className} ${sfMono.variable} bg-bg-light text-text antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
